### PR TITLE
Support for nsq v1.x.x

### PR DESCRIPTION
**Pull request by mbobakov**
Hello.
From nsq version v1.0.0 stats response was changed

### CODE REVIEW

**Comment by heltonmarx** [comment]
You're right, but it's necessary add more one thing:
```go
func getNsqdStats(nsqdURL string) (*stats, error) {
	host, err := url.Parse(nsqdURL + "/stats")
	if err != nil {
		return nil, err
	}
	params := url.Values{}
	params.Set("format", "json")
	host.RawQuery = params.Encode()

	resp, err := http.Get(host.String())
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
        ...
}
```
Following the [documentation](http://nsq.io/components/nsqd.html#get-stats), the default return is `text`.  So, that's why you should add the params with `json` format.

**Comment by mbobakov** [comment]
I think it should be enough for url building.
https://github.com/lovoo/nsq_exporter/blob/master/main.go#L90

**Comment by heltonmarx** [comment]
Oh...sorry, my mistake. You're right.

**Review by heltonmarx — APPROVED** [review]

**Comment by timonwong** [comment]
Besides, I think you should set `Accept` header to `application/vnd.nsq; version=1.0`
Then even on older nsqd, it will work

**Comment by mbobakov** [comment]
What is the reason for this header for this PR ?  Maybe it should be go to another Issue?

**Comment by timonwong** [comment]
IMHO, it's better maintain compatibility while adding support to nsq v1+.
Once that header is introduced, you can say both nsqd v0.2.29+ and v1+ are
supported at the same time, instead of dropping support to older nsqd.

**Comment by jwitko** [comment]
Any chance of this being merged?

**Comment by mbobakov** [comment]
if it is necessary , i can implement `Accept` header to `application/vnd.nsq; version=1.0`
But i think is not blocker for merge.
@heltonmarx Can you merge this PR?

**Comment by jwitko** [comment]
@mbobakov @heltonmarx If it adds any confidence to this PR, I merged and built it locally months ago and have been using it ever since without any issues.  I was hosting that local binary in S3 privately and pulling from there for my configuration management.  The reason I commented today is because I was refactoring my config management code and trying to remove S3 pulls for custom binaries and go back to the source.

**Comment by tommy-muehle** [comment]
Hi, this pull request is being closed because this repo is (or will be) archived and is not maintained since years.

**Pull request closed without merging**
