### PR TITLE
fix serialization

### PR DESCRIPTION
**Pull request by jhutchins**
I don't know about anyone else, but my nsq image (`nsqio/nsq:v1.0.0-compat`) doesn't output its stats in a form that matches the current serialization.

### CODE REVIEW

**Review by tjsampson — APPROVED** [review]
Looks good to me.

**Comment by tjsampson** [comment]
It would be nice to get this merged. This bug makes the exporter pretty useless without the stats.

**Comment by kavirajk** [comment]
I agree  @tjsampson can someone please merge this and release may be?

/cc @tecbot @peterbourgon(sorry, I saw you did last release :))

**Comment by tommy-muehle** [comment]
Hi, this pull request is being closed because this repo is (or will be) archived and is not maintained since years.

**Pull request closed without merging**
